### ISSUE TITLE
Full report "field larger than field limit"

### ISSUE THREAD

**Issue by mzur** [biigle/reports#79]
Investigate this error and prevent it from happening again:
```
The report script 'full_report' failed with exit code 1:
    Traceback (most recent call last):
      File "/var/www/vendor/biigle/reports/src/config/../resources/scripts/full_report.py", line 58, in <module>
        add_sheet(csv_path, i)
      File "/var/www/vendor/biigle/reports/src/config/../resources/scripts/full_report.py", line 22, in add_sheet
        for row in csv_reader:
    _csv.Error: field larger than field limit (131072)
```

**Comment by mzur** [comment]
This can be fixed by [increasing the field size limit](https://stackoverflow.com/a/15063941/1796523).
